name: CI

on:
  push:
    branches:
      - "master"
  pull_request:
  workflow_dispatch:

jobs:
  ci:
    uses: angr/ci-settings/.github/workflows/angr-ci.yml@master

  test:
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
        os: [ubuntu-22.04, macos-14, windows-2022]
      fail-fast: false
    name: Test on ${{ matrix.os }} with Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: ./pysoot
    steps:
    - name: Checkout Pysoot
      uses: actions/checkout@v4
      with:
        path: pysoot
    - name: Checkout binaries
      uses: actions/checkout@v4
      with:
        repository: angr/binaries
        path: binaries
        sparse-checkout: |
          tests/java/simple1.jar
          tests/java/simple2.jar
          tests/java/exceptions1.jar
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '21'

    - name: Setup uv
      uses: astral-sh/setup-uv@v7
      with:
        activate-environment: true
        python-version: ${{ matrix.python-version }}
        working-directory: pysoot

    - name: uv sync
      run: uv sync

    - name: Run tests
      run: pytest
